### ISSUE TITLE
PgHero 3

### ISSUE THREAD

**Issue by ankane** [ankane/pghero#415]
Please create a new issue to discuss any ideas or share your own.

`edge` branch

Plan

- [x] (breaking) Make `capture_query_stats`  only reset stats for database instead of instance in Postgres 12+
- [x] (breaking) Make `reset_query_stats` only reset stats for current database (use new `reset_instance_query_stats` method to reset for entire instance)
- [ ] Only suggest removing large unused indexes on space page
- [x] Drop support for Rails < 6 and Ruby < 2.7
- [x] Drop support for pg_query < 2
- [x] Drop Linux packages for EOL distributions (Ubuntu 16.04, Debian 8/9, RHEL 7, SUSE 12)
- [ ] Switch visualize link to Postgres Explain Visualizer 2 - #369
- [x] (maybe) Make visualize link configurable - #419 
- [ ] (maybe) Normalize query stats to save space - #381 

Other ideas

- [x] Add Linux package for Ubuntu 22.04
- [ ] Add support for system stats for self-hosted Postgres (`pg_proctab`, `file_fdw`, or another method)
